version: '3.5'

services:
  toontust-core-postgres:
    container_name: "toontust-core-postgres"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hightech
      POSTGRES_USER: hightech
      POSTGRES_DB: toontust-core-db
