### Create Product

POST http://localhost:8080/api/v1/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id": "A0001",
  "name": "MacBook Pro 14",
  "price": 30000000,
  "quantity": 10
}

### Create Product Invalid

POST http://localhost:8080/api/v1/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id": "",
  "name": "",
  "price": 0,
  "quantity": -10
}

### Get Product

GET http://localhost:8080/api/v1/products/A0001
X-Api-Key: SECRET
Accept: application/json

### Get Product Not Found

GET http://localhost:8080/api/v1/products/A0002
X-Api-Key: SECRET
Accept: application/json

### Update Product

PUT http://localhost:8080/api/v1/products/A0001
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "MacBook Pro 16",
  "price": 35000000,
  "quantity": 8
}

### Update Product Not Found

PUT http://localhost:8080/api/v1/products/INVALID
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "MacBook Pro 16",
  "price": 35000000,
  "quantity": 8
}

### Update Product with invalid body

PUT http://localhost:8080/api/v1/products/A0001
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "price": 0,
  "quantity": -6
}

### Delete Product

DELETE http://localhost:8080/api/v1/products/A0001
X-Api-Key: SECRET
Accept: application/json

### List Product

GET http://localhost:8080/api/v1/products
X-Api-Key: SECRET
Accept: application/json

### List Product with size parameter

GET http://localhost:8080/api/v1/products?size=5
X-Api-Key: SECRET
Accept: application/json

### List Product with size & page parameter

GET http://localhost:8080/api/v1/products?size=5&page=1
X-Api-Key: SECRET
Accept: application/json

### Request without X-Api-Key

GET http://localhost:8080/api/v1/products
Accept: application/json

### Request with invalid X-Api-Key

GET http://localhost:8080/api/v1/products
X-Api-Key: SALAH
Accept: application/json
